# Generated by Django 4.0.5 on 2022-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_d_key_user_e_key_user_n_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
