# Generated by Django 4.0.5 on 2022-06-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_student_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='d_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='e_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='n_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
