# Generated by Django 4.0.5 on 2022-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=4)),
                ('teacher_id', models.IntegerField(choices=[[10, 'nguyen Vna C'], [12, 'Nguyen Van B'], [13, 'Nguyen Van F']])),
                ('course_name', models.CharField(max_length=255)),
                ('final_mark', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
