# Generated by Django 4.0.5 on 2022-07-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitblock',
            name='student_name',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AlterField(
            model_name='waitblock',
            name='teacher_id',
            field=models.IntegerField(choices=[[15, 'Pham Van AA']]),
        ),
    ]
