# Generated by Django 4.0.5 on 2022-09-16 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cert', '0002_waitblock_student_name_alter_waitblock_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitblock',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='waitblock',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
